#!/usr/bin/env python3

from pathlib import Path
from subprocess import run


raw = Path('../_raw-images')
destination = Path('../images')

destination_width = 400
original = raw/'graphics/alles-ist-kunst.png'



# set hcw 484 # half column width

# convert $source/misc/typewriter.png -resize 484 $destination/misc/typewriter.png
